# config/meta.yml

meta_product_name: "PlanYourNight."
meta_title: "Best places to go out"
meta_description: "Plan your night in Berlin based on your tastes and budget at over 40 venues. No Search Fees. "
meta_image: "PYN.png" # should exist in `app/assets/images/`
twitter_account: "@PlanNight"   # required for Twitter Cards
